# Generated by Django 3.2.8 on 2021-11-01 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211101_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('a78518b6-6b5e-40bc-8af9-0b99d928c72f'), editable=False),
        ),
    ]
