# Generated by Django 3.2.8 on 2021-11-01 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('451774d1-e14c-43f0-8354-ed30280f7e81'), editable=False),
        ),
    ]
