# Generated by Django 3.2.8 on 2021-11-01 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('6fc7a0ac-9c69-4c68-9f91-474b06384a0f'), editable=False),
        ),
    ]
