# Generated by Django 3.2.8 on 2021-11-01 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('5a80a94a-c400-4980-b0e9-1affad2b883c'), editable=False),
        ),
    ]
