# Generated by Django 3.2.8 on 2021-11-01 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('34d9fa69-e291-4633-9909-a61255fd7afb'), editable=False),
        ),
    ]
